In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

Calculate total sales from units and price per unit using matrix multiplication

In [4]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In above case numpy is using broadcasting so it expands price_per_unit array from 1 row, 3 columns to 3 row and 3 columns. Correct way to do matrix multiplication is to use dot product as shown below

In [6]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

Solution 1: Convert USD revenues to INR

In [7]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [8]:
revenues_in_inr = revenues_usd * 75
revenues_in_inr


array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Solution 2: Calculate total flowers sale every month for divine flowers shop

In [12]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [13]:
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount

array([1900, 2640, 1430])