In [65]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [66]:
#one_hot("amazing restaurant",300)

In [67]:
one_hot("amazing restaurant",30)

[15, 22]

In [68]:

vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[21, 17], [15, 22], [3, 8], [9, 21, 23], [28, 25, 5], [15, 17], [13, 25, 7], [9, 13], [9, 17], [21, 1]]


In [69]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[21 17  0  0]
 [15 22  0  0]
 [ 3  8  0  0]
 [ 9 21 23  0]
 [28 25  5  0]
 [15 17  0  0]
 [13 25  7  0]
 [ 9 13  0  0]
 [ 9 17  0  0]
 [21  1  0  0]]


In [70]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [71]:
X = padded_reviews
y = sentiment


In [72]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_7 (Flatten)         (None, 20)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [73]:
model.fit(X, y, epochs=50, verbose=0)

In [74]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 143ms/step - loss: 0.6347 - accuracy: 0.9000


0.8999999761581421

In [75]:
 model.get_layer('embedding').get_weights()[0]

array([[-0.0328028 ,  0.06114512, -0.05735191, -0.06639051,  0.00064595],
       [-0.00244514, -0.0240403 ,  0.07820133, -0.04792291, -0.08840193],
       [-0.03177239, -0.00066831,  0.00531135, -0.03850002,  0.00816268],
       [-0.08057194, -0.08359583,  0.09778819,  0.09510282, -0.00340468],
       [ 0.0164862 , -0.00626834, -0.01152631, -0.01905786, -0.04731256],
       [ 0.00623542, -0.0333962 ,  0.07539998,  0.01100754, -0.09307864],
       [-0.01776654, -0.02758559, -0.00628362,  0.04169183, -0.00455416],
       [ 0.00200538,  0.07618485, -0.01194313, -0.00652394,  0.10069363],
       [ 0.05188655,  0.09742997, -0.06441776,  0.06688541, -0.00068397],
       [ 0.09407728,  0.06060587, -0.03860226, -0.08032716,  0.02019849],
       [ 0.03345687, -0.0462781 ,  0.0336448 , -0.04973434, -0.00267377],
       [ 0.01766907, -0.02889105,  0.01583396, -0.0287753 , -0.04860714],
       [ 0.04373672, -0.03422838,  0.00580387, -0.04347476,  0.03157309],
       [-0.07776693, -0.05678946, -0.0

In [76]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [77]:
weights[11]

array([ 0.01766907, -0.02889105,  0.01583396, -0.0287753 , -0.04860714],
      dtype=float32)

In [78]:
weights[3]

array([-0.08057194, -0.08359583,  0.09778819,  0.09510282, -0.00340468],
      dtype=float32)